const fs = require("fs");
const path = require("path");
const axios = require("axios");
const FormData = require("form-data");
const { PDFDocument, rgb } = require("pdf-lib");
const Verification = require("../models/Verification");

function getOcrBaseUrl() {
  const url = process.env.PYTHON_OCR_URL || "http://127.0.0.1:8000/ocr";
  return url.replace(/\/ocr\/?$/, "");
}

async function runOcr(filePath, docType) {
  const absoluteFilePath = path.resolve(filePath);

  try {
    const form = new FormData();
    form.append("file", fs.createReadStream(absoluteFilePath));
    form.append("docType", docType);

    const response = await axios.post(`${getOcrBaseUrl()}/ocr/upload`, form, {
      headers: form.getHeaders(),
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      timeout: 120000
    });

    return response.data;
  } catch {
    const response = await axios.post(`${getOcrBaseUrl()}/ocr`, {
      filePath: absoluteFilePath,
      docType
    });

    return response.data;
  }
}

function normalizeName(name) {
  if (!name) return "";
  return String(name).toLowerCase().replace(/[^a-z]/g, "");
}

function calculateScore(checks, extractedData) {
  let score = 100;

  if (!checks.nameMatch) score -= 20;
  if (!checks.dobMatch) score -= 20;
  if (checks.missingFields) score -= 15;
  if (checks.blurryDocument) score -= 10;
  if (checks.duplicateDocument) score -= 10;

  const docs = ["aadhaar", "pan", "resume", "marksheet"];

  docs.forEach((doc) => {
    const data = extractedData?.[doc];

    if (data) {
      if (data.documentTypeMatch === false) score -= 10;

      if ((data.authenticityScore || 0) < 50) score -= 15;
      else if ((data.authenticityScore || 0) < 75) score -= 8;

      if ((data.qualityScore || 0) < 50) score -= 10;
      else if ((data.qualityScore || 0) < 75) score -= 5;
    }
  });

  return Math.max(score, 0);
}

function getRiskLevel(score) {
  if (score >= 80) return "Low Risk";
  if (score >= 50) return "Medium Risk";
  return "High Risk";
}

function getRecommendation(score) {
  if (score >= 80) return "Verified";
  if (score >= 50) return "Needs Manual Review";
  return "Rejected";
}

function safeJoinArray(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return "Not found";
  return arr.join(", ");
}

async function generatePDF(data) {
  const pdfDoc = await PDFDocument.create();

  let page = pdfDoc.addPage([600, 800]);
  let y = 750;

  const aadhaar = data.extractedData?.aadhaar || {};
  const pan = data.extractedData?.pan || {};
  const resume = data.extractedData?.resume || {};
  const marksheet = data.extractedData?.marksheet || {};

  const addNewPageIfNeeded = () => {
    if (y < 90) {
      page = pdfDoc.addPage([600, 800]);
      y = 750;
    }
  };

  const drawHeading = (text) => {
    addNewPageIfNeeded();

    page.drawText(String(text), {
      x: 50,
      y,
      size: 16,
      color: rgb(0, 0, 0)
    });

    y -= 25;
  };

  const drawText = (text) => {
    addNewPageIfNeeded();

    const safeText = String(text || "").slice(0, 95);

    page.drawText(safeText, {
      x: 70,
      y,
      size: 10,
      color: rgb(0, 0, 0)
    });

    y -= 16;
  };

  const drawLine = () => {
    addNewPageIfNeeded();

    page.drawLine({
      start: { x: 50, y },
      end: { x: 550, y },
      thickness: 1,
      color: rgb(0.75, 0.75, 0.75)
    });

    y -= 22;
  };

  const drawFooter = () => {
    page.drawText(`Generated on: ${new Date().toLocaleString()}`, {
      x: 50,
      y: 50,
      size: 9,
      color: rgb(0.25, 0.25, 0.25)
    });

    page.drawText("Generated by TrustLens AI Verification System", {
      x: 50,
      y: 35,
      size: 9,
      color: rgb(0.25, 0.25, 0.25)
    });
  };

  page.drawText("TrustLens Verification Report", {
    x: 50,
    y,
    size: 24,
    color: rgb(0, 0, 0)
  });

  y -= 25;

  page.drawText("AI-Powered Identity Verification & Trust Scoring Platform", {
    x: 50,
    y,
    size: 11,
    color: rgb(0.25, 0.25, 0.25)
  });

  y -= 25;
  drawLine();

  drawHeading("Verification Result");
  drawText(`Trust Score: ${data.trustScore}/100`);
  drawText(`Risk Level: ${data.riskLevel}`);
  drawText(`Recommendation: ${data.recommendation}`);
  drawLine();

  drawHeading("Candidate Information");
  drawText(`Aadhaar Name: ${aadhaar.name || "Not found"}`);
  drawText(`Aadhaar DOB: ${aadhaar.dob || "Not found"}`);
  drawText(`Aadhaar Number: ${aadhaar.idNumber || "Not found"}`);
  drawText(`PAN Name: ${pan.name || "Not found"}`);
  drawText(`PAN DOB: ${pan.dob || "Not found"}`);
  drawText(`PAN Number: ${pan.idNumber || "Not found"}`);
  drawLine();

  drawHeading("Resume & Academic Information");
  drawText(`Resume Name: ${resume.name || "Not found"}`);
  drawText(`Resume Email: ${resume.email || "Not found"}`);
  drawText(`Resume Phone: ${resume.phone || "Not found"}`);
  drawText(`Detected Skills: ${safeJoinArray(resume.skills)}`);
  drawText(`Employability Score: ${resume.employabilityScore || 0}/100`);
  drawText(`Recommended Roles: ${safeJoinArray(resume.candidateInsights?.recommendedRoles)}`);
  drawText(`Strengths: ${safeJoinArray(resume.candidateInsights?.strengths)}`);
  drawText(`Weaknesses: ${safeJoinArray(resume.candidateInsights?.weaknesses)}`);
  drawText(`Marksheet Name: ${marksheet.name || "Not found"}`);
  drawLine();

  drawHeading("Document Authenticity Summary");
  drawText(`Aadhaar Type Match: ${aadhaar.documentTypeMatch ? "Yes" : "No"}`);
  drawText(`Aadhaar Authenticity Score: ${aadhaar.authenticityScore || 0}/100`);
  drawText(`Aadhaar Quality Score: ${aadhaar.qualityScore || 0}/100`);
  drawText(`PAN Type Match: ${pan.documentTypeMatch ? "Yes" : "No"}`);
  drawText(`PAN Authenticity Score: ${pan.authenticityScore || 0}/100`);
  drawText(`PAN Quality Score: ${pan.qualityScore || 0}/100`);
  drawText(`Resume Type Match: ${resume.documentTypeMatch ? "Yes" : "No"}`);
  drawText(`Resume Authenticity Score: ${resume.authenticityScore || 0}/100`);
  drawText(`Marksheet Type Match: ${marksheet.documentTypeMatch ? "Yes" : "No"}`);
  drawText(`Marksheet Authenticity Score: ${marksheet.authenticityScore || 0}/100`);
  drawLine();

  drawHeading("Verification Checks");
  drawText(`Name Match: ${data.checks?.nameMatch ? "Yes" : "No"}`);
  drawText(`DOB Match: ${data.checks?.dobMatch ? "Yes" : "No"}`);
  drawText(`Missing Fields: ${data.checks?.missingFields ? "Yes" : "No"}`);
  drawText(`Blurry Document: ${data.checks?.blurryDocument ? "Yes" : "No"}`);
  drawText(`Duplicate Document: ${data.checks?.duplicateDocument ? "Yes" : "No"}`);
  drawLine();

  drawHeading("Final Decision");
  drawText(
    `This candidate is classified as ${data.riskLevel} with recommendation: ${data.recommendation}.`
  );

  drawFooter();

  const pdfBytes = await pdfDoc.save();

  const reportsDir = path.join(__dirname, "../reports");

if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

const fileName = `report_${Date.now()}.pdf`;
const reportPath = path.join(reportsDir, fileName);

fs.writeFileSync(reportPath, pdfBytes);

return `/reports/${fileName}`;


exports.verifyDocuments = async (req, res) => {
  try {
    const files = req.files || {};

    const aadhaarFile = files.aadhaar?.[0];
    const panFile = files.pan?.[0];
    const resumeFile = files.resume?.[0];
    const marksheetFile = files.marksheet?.[0];

    const uploadedFiles = {
      aadhaar: aadhaarFile,
      pan: panFile,
      resume: resumeFile,
      marksheet: marksheetFile
    };

    const extractedData = {};

    for (const key in uploadedFiles) {
      if (uploadedFiles[key]) {
        try {
          extractedData[key] = await runOcr(uploadedFiles[key].path, key);
        } catch (ocrError) {
          extractedData[key] = {
            docType: key,
            detectedType: "unknown",
            documentTypeMatch: false,
            name: "",
            dob: "",
            idNumber: "",
            email: "",
            phone: "",
            qualityScore: 0,
            isBlurry: true,
            qualityRemark: "OCR service failed",
            authenticityScore: 0,
            authenticityChecks: [ocrError.message],
            skills: [],
            employabilityScore: 0,
            candidateInsights: {
              strengths: [],
              weaknesses: ["Document could not be processed"],
              recommendedRoles: []
            },
            rawText: ""
          };
        }
      }
    }

    const aadhaarName = normalizeName(extractedData?.aadhaar?.name || "");
    const panName = normalizeName(extractedData?.pan?.name || "");
    const resumeName = normalizeName(extractedData?.resume?.name || "");
    const marksheetName = normalizeName(extractedData?.marksheet?.name || "");

    const aadhaarDOB = extractedData?.aadhaar?.dob || "";
    const panDOB = extractedData?.pan?.dob || "";

    const nameMatch =
      aadhaarName &&
      panName &&
      (
        aadhaarName === panName ||
        panName.includes(aadhaarName) ||
        aadhaarName.includes(panName) ||
        resumeName.includes(aadhaarName) ||
        aadhaarName.includes(resumeName) ||
        marksheetName.includes(aadhaarName) ||
        aadhaarName.includes(marksheetName)
      );

    const dobMatch =
      aadhaarDOB &&
      panDOB &&
      aadhaarDOB === panDOB;

    const missingFields =
      !extractedData?.aadhaar?.name ||
      !extractedData?.aadhaar?.dob ||
      !extractedData?.aadhaar?.idNumber ||
      !extractedData?.pan?.name ||
      !extractedData?.pan?.dob ||
      !extractedData?.pan?.idNumber;

    const blurryDocument =
      Boolean(extractedData?.aadhaar?.isBlurry) ||
      Boolean(extractedData?.pan?.isBlurry) ||
      Boolean(extractedData?.resume?.isBlurry) ||
      Boolean(extractedData?.marksheet?.isBlurry);

    const duplicateQuery = [];

    if (extractedData?.aadhaar?.idNumber) {
      duplicateQuery.push({
        "extractedData.aadhaar.idNumber": extractedData.aadhaar.idNumber
      });
    }

    if (extractedData?.pan?.idNumber) {
      duplicateQuery.push({
        "extractedData.pan.idNumber": extractedData.pan.idNumber
      });
    }

    let duplicateDocument = false;

    try {
      if (duplicateQuery.length > 0) {
        const existingDuplicate = await Verification.findOne({
          $or: duplicateQuery
        });

        duplicateDocument = Boolean(existingDuplicate);
      }
    } catch (err) {
      duplicateDocument = false;
    }

    const checks = {
      nameMatch: Boolean(nameMatch),
      dobMatch: Boolean(dobMatch),
      missingFields: Boolean(missingFields),
      blurryDocument: Boolean(blurryDocument),
      duplicateDocument
    };

    const trustScore = calculateScore(checks, extractedData);
    const riskLevel = getRiskLevel(trustScore);
    const recommendation = getRecommendation(trustScore);

    const reportPath = await generatePDF({
      checks,
      trustScore,
      riskLevel,
      recommendation,
      extractedData
    });

    const verification = await Verification.create({
      userId: req.user?.id || null,
      aadhaarFile: aadhaarFile?.path,
      panFile: panFile?.path,
      resumeFile: resumeFile?.path,
      marksheetFile: marksheetFile?.path,
      extractedData,
      checks,
      trustScore,
      riskLevel,
      recommendation,
      reportPath
    });

    res.status(201).json({
      message: "Verification completed",
      verification
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Verification failed",
      error: error.message
    });
  }
};

exports.getAllVerifications = async (req, res) => {
  try {
    const data = await Verification.find().sort({ createdAt: -1 });
    res.json(data);
  } catch (error) {
    res.status(500).json({
      message: "Failed to fetch records",
      error: error.message
    });
  }
};

exports.getMyVerifications = async (req, res) => {
  try {
    const data = await Verification.find({ userId: req.user.id }).sort({
      createdAt: -1
    });
    res.json(data);
  } catch (error) {
    res.status(500).json({
      message: "Failed to fetch your verifications",
      error: error.message
    });
  }
};

exports.getAnalytics = async (req, res) => {
  try {
    const records = await Verification.find().sort({ createdAt: -1 });

    const total = records.length;
    const avgScore =
      total > 0
        ? Math.round(records.reduce((s, r) => s + (r.trustScore || 0), 0) / total)
        : 0;

    const byRisk = {
      low: records.filter((r) => r.riskLevel === "Low Risk").length,
      medium: records.filter((r) => r.riskLevel === "Medium Risk").length,
      high: records.filter((r) => r.riskLevel === "High Risk").length
    };

    const byRecommendation = {
      verified: records.filter((r) => r.recommendation === "Verified").length,
      manualReview: records.filter((r) => r.recommendation === "Needs Manual Review").length,
      rejected: records.filter((r) => r.recommendation === "Rejected").length
    };

    const byRecruiterStatus = {
      pending: records.filter((r) => (r.recruiterStatus || "Pending Review") === "Pending Review").length,
      approved: records.filter((r) => r.recruiterStatus === "Approved").length,
      rejected: records.filter((r) => r.recruiterStatus === "Rejected").length,
      clarification: records.filter((r) => r.recruiterStatus === "Needs Clarification").length
    };

    const last7Days = records.filter((r) => {
      const d = new Date(r.createdAt);
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      return d >= weekAgo;
    }).length;

    const monthlyTrend = [];
    for (let i = 5; i >= 0; i--) {
      const date = new Date();
      date.setMonth(date.getMonth() - i);
      const label = date.toLocaleString("default", { month: "short" });
      const count = records.filter((r) => {
        const d = new Date(r.createdAt);
        return d.getMonth() === date.getMonth() && d.getFullYear() === date.getFullYear();
      }).length;
      monthlyTrend.push({ month: label, count });
    }

    res.json({
      total,
      avgScore,
      last7Days,
      byRisk,
      byRecommendation,
      byRecruiterStatus,
      monthlyTrend,
      passRate: total > 0 ? Math.round((byRecommendation.verified / total) * 100) : 0
    });
  } catch (error) {
    res.status(500).json({
      message: "Failed to fetch analytics",
      error: error.message
    });
  }
};

exports.getVerificationById = async (req, res) => {
  try {
    const verification = await Verification.findById(req.params.id);

    if (!verification) {
      return res.status(404).json({
        message: "Verification record not found"
      });
    }

    if (
      req.user.role === "candidate" &&
      verification.userId &&
      String(verification.userId) !== String(req.user.id)
    ) {
      return res.status(403).json({ message: "Access denied" });
    }

    res.json(verification);
  } catch (error) {
    res.status(500).json({
      message: "Failed to fetch verification record",
      error: error.message
    });
  }
};


exports.updateRecruiterReview = async (req, res) => {
  try {
    const { recruiterStatus, recruiterNotes } = req.body;

    const allowedStatuses = [
      "Pending Review",
      "Approved",
      "Rejected",
      "Needs Clarification"
    ];

    if (!allowedStatuses.includes(recruiterStatus)) {
      return res.status(400).json({
        message: "Invalid recruiter status"
      });
    }

    const verification = await Verification.findByIdAndUpdate(
      req.params.id,
      {
        recruiterStatus,
        recruiterNotes,
        reviewedAt: new Date(),
        reviewedBy: req.user.id
      },
      { new: true }
    );

    if (!verification) {
      return res.status(404).json({
        message: "Verification record not found"
      });
    }

    res.json({
      message: "Recruiter review updated",
      verification
    });
  } catch (error) {
    res.status(500).json({
      message: "Failed to update recruiter review",
      error: error.message
    });
  }
};

exports.deleteVerification = async (req, res) => {
  try {
    const verification = await Verification.findByIdAndDelete(req.params.id);

    if (!verification) {
      return res.status(404).json({
        message: "Verification record not found"
      });
    }

    res.json({
      message: "Verification record deleted successfully"
    });
  } catch (error) {
    res.status(500).json({
      message: "Failed to delete verification record",
      error: error.message
    });
  }
};